martingerdzhev\ImageAnnotatorBundle\Entity\AnnotationType:
    type: entity
    table: annotation_type
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
