martingerdzhev\ImageAnnotatorBundle\Entity\AnnotationType:
    type: entity
    table: annotation_type
    repositoryClass: martingerdzhev\ImageAnnotatorBundle\Entity\AnnotationTypeRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            unique: true
