martingerdzhev\ImageAnnotatorBundle\Entity\Annotation:
    type: entity
    table: annotation
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        dateCreated:
            type: datetime
        dateModified:
            type: datetime
            nullable: true
            
    manyToOne:
        creator:
            targetEntity: User
            joinColumn:
                name: creator_id
                referencedColumnName: id
        type:
            targetEntity: AnnotationType
            joinColumn:
                name: type_id
                referencedColumnName: id
        image:
            targetEntity: Image
            inversedBy: annotations
    lifecycleCallbacks: {  }
