martingerdzhev\ImageAnnotatorBundle\Entity\Dataset:
    type:  entity
    table: dataset
    repositoryClass: martingerdzhev\ImageAnnotatorBundle\Entity\DatasetRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        createdDate:
            type: datetime
        name:
            type: string
    lifecycleCallbacks: 
        prePersist: [setCreatedDateToNow]
    oneToMany:
        images:
            targetEntity: Image
            mappedBy: dataset
            orderBy:
                id: DESC
                
    manyToOne:
        creator:
            targetEntity: User
            joinColumn:
                name: creator_id
                referencedColumnName: id
  
    manyToMany:
        annotationTypes:
            targetEntity: AnnotationType
            joinTable:
                name: dataset_annotation_types
                joinColumns:
                  dataset_id:
                    referencedColumnName: id
                inverseJoinColumns:
                  annotation_type_id:
                    referencedColumnName: id
                    unique: true
              