martingerdzhev\ImageAnnotatorBundle\Entity\Image:
    type:  entity
    table: Image
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:  #user given title of the media
            type: string
            length: 255
            nullable: true;
                
    oneToOne:
        metaData: #metadata object to hold the information about the data
            targetEntity: MetaData
            joinColumn:
                name: meta_data
                referencedColumnName: id
            cascade: ["all"]
                
        resource: #resource object to hold the data
            targetEntity: ResourceFile
            joinColumn:
                name: resource_id
                referencedColumnName: id
            cascade: ["all"]

    oneToMany:
        annotations:
            targetEntity: Annotation
            mappedBy: image
            orderBy:
                dateCreated: DESC
    manyToOne:
        dataset:
            targetEntity: Dataset
            inversedBy: images
