martingerdzhev\ImageAnnotatorBundle\Entity\ResourceFile:
    type:  entity
    table: resource_file
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        path:
            type: string
            length: 255
            nullable: true
               
    lifecycleCallbacks:
        prePersist: [ preUpload ]
        postPersist: [ upload ]
        preUpdate: [ preUpload ]
        postUpdate: [ upload ]
        preRemove: [ storeFilenameForRemove ]
        postRemove: [ removeUpload ]
        