martingerdzhev\ImageAnnotatorBundle\Entity\UserProfile:
    type:   entity
    table:  user_profile
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
     
    fields: 
        firstName:
            type: string
            length: 255
        lastName:
            type: string
            length: 255
        institution:
            type: string
            length: 255
            nullable: true
        city:
            type: string
            length: 255
            nullable: true
        country:
            type: string
            length: 255
            nullable: true
            
