<?php

namespace martingerdzhev\ImageAnnotatorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnnotationTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnotationTypeRepository extends EntityRepository
{
	
	public function findNotInDataset($dataset)
	{
		$query = $this->getEntityManager()->createQuery('
                    SELECT a
					FROM ImageAnnotatorBundle:Dataset d
					JOIN d.annotationTypes e 
					JOIN ImageAnnotatorBundle:AnnotationType a
					WHERE d.id = :did
					AND	a.id != e.id
                ')->setParameter('did', $dataset->getId());
	
		return $query->getResult();
	}
}
