image_annotator:
    resource: "@ImageAnnotatorBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@ImageAnnotatorBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@ImageAnnotatorBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@ImageAnnotatorBundle/Resources/config/routing/resetting.xml"
    prefix: /password-reset

fos_user_change_password:
    resource: "@ImageAnnotatorBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
fos_user_profile_show:
    resource: "@ImageAnnotatorBundle/Resources/config/routing/profile.xml"
    prefix: /profile
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
