image_annotator_annotations_list: 
  pattern: /
  defaults: { _controller: ImageAnnotatorBundle:AnnotationsGateway:gateway }

image_annotator_annotations_list_images: 
  pattern: /images
  defaults: { _controller: ImageAnnotatorBundle:AnnotationsGateway:gatewayImages }

image_annotator_annotations_create: 
  pattern: /create
  defaults: { _controller: ImageAnnotatorBundle:AnnotationsGateway:gatewayCreate }
  
image_annotator_annotation_preview:
  pattern: /preview/{annotationId}
  defaults: { _controller: ImageAnnotatorBundle:AnnotationsGateway:previewAnnotation }
  requirements:
    annotationId: \d+
  options:
    expose: true

image_annotator_annotation_update:
  pattern: /update/{annotationId}
  defaults: { _controller: ImageAnnotatorBundle:AnnotationsGateway:updateAnnotation }
  requirements:
    _method:  POST
    annotationId: \d+
  options:
    expose: true

image_annotator_annotation_remove:
  pattern: /delete/{annotationId}
  defaults: { _controller: ImageAnnotatorBundle:AnnotationsGateway:deleteAnnotation }
  requirements:
    _method:  POST
    annotationId: \d+
  options:
    expose: true

image_annotator_annotation_add:
  pattern: /add/{imageId}
  defaults: { _controller: ImageAnnotatorBundle:AnnotationsGateway:addAnnotation, url: null }
  requirements:
    _method:  POST
    imageId: \d+
  options:
    expose: true
    
image_annotator_annotation_approve:
  pattern: /approve/{annotationId}
  defaults: { _controller: ImageAnnotatorBundle:AnnotationsGateway:approveAnnotation }
  requirements:
    _method:  POST
    annotationId: \d+
  options:
    expose: true

image_annotator_annotation_reject:
  pattern: /reject/{annotationId}
  defaults: { _controller: ImageAnnotatorBundle:AnnotationsGateway:rejectAnnotation }
  requirements:
    _method:  POST
    annotationId: \d+
  options:
    expose: true