image_annotator_dataset_gateway:
  pattern: /
  defaults: { _controller: ImageAnnotatorBundle:DatasetGateway:gateway }
  options:
    expose: true
    
image_annotator_dataset_browse:
  pattern: /{datasetId}/browse
  defaults: { _controller: ImageAnnotatorBundle:DatasetGateway:browse }
  requirements:
    datasetId: \d+
  options:
    expose: true
    
image_annotator_dataset_annotation_types_show:
  pattern: /{datasetId}/annotationTypes/show/{type}
  defaults: { _controller: ImageAnnotatorBundle:DatasetGateway:showAnnotationTypes, type: 'all' }
  requirements:
    _method:  POST
  options:
    expose: true
    
image_annotator_dataset_annotation_types_create:
  pattern: /{datasetId}/annotationTypes/create
  defaults: { _controller: ImageAnnotatorBundle:DatasetGateway:createAnnotationType }
  requirements:
    datasetId: \d+
    _method:  POST
  options:
    expose: true
    
image_annotator_dataset_annotation_types_add:
  pattern: /{datasetId}/annotationTypes/annotationTypeId
  defaults: { _controller: ImageAnnotatorBundle:DatasetGateway:addAnnotationType }
  requirements:
    _method:  POST
    datasetId: \d+
  options:
    expose: true
    
image_annotator_dataset_annotate:
  pattern: /{datasetId}/annotate
  defaults: { _controller: ImageAnnotatorBundle:DatasetGateway:annotate }
  requirements:
    datasetId: \d+
  options:
    expose: true

image_annotator_dataset_create:
  pattern: /create
  defaults: { _controller: ImageAnnotatorBundle:DatasetGateway:create }
  options:
    expose: true

image_annotator_dataset_delete:
  pattern: /{datasetId}/delete
  defaults: { _controller: ImageAnnotatorBundle:DatasetGateway:delete, url: null }
  requirements:
    _method:  POST
    datasetId: \d+
  options:
    expose: true

image_annotator_dataset_update:
  pattern: /{datasetId}/update
  defaults: { _controller: ImageAnnotatorBundle:DatasetGateway:update, url: null }
  requirements:
    _method:  POST
    datasetId: \d+
  options:
    expose: true
