image_annotator_image_gateway:
  pattern: /
  defaults: { _controller: ImageAnnotatorBundle:ImageGateway:gateway }
  options:
    expose: true
    
image_annotator_image_preview:
  pattern: /preview/{imageId}
  defaults: { _controller: ImageAnnotatorBundle:ImageGateway:view }
  requirements:
    imageId: \d+
  options:
    expose: true

image_annotator_image_remove:
  pattern: /delete/{imageId}
  defaults: { _controller: ImageAnnotatorBundle:ImageGateway:deleteImage }
  requirements:
    _method:  POST
    imageId: \d+
  options:
    expose: true

image_annotator_image_add_image:
  pattern: /add
  defaults: { _controller: ImageAnnotatorBundle:AddFileGateway:addImage, url: null }
  options:
    expose: true

image_annotator_image_add_image_upload:
  pattern: /add/upload
  defaults: { _controller: ImageAnnotatorBundle:AddFileGateway:addImageUpload, url: null }
  options:
    expose: true

image_annotator_image_add_image_google:
  pattern: /add/google
  defaults: { _controller: ImageAnnotatorBundle:AddFileGateway:addImageGoogle, url: null }
  options:
    expose: true

image_annotator_image_add_image_flickr:
  pattern: /add/flickr
  defaults: { _controller: ImageAnnotatorBundle:AddFileGateway:addImageFlickr, url: null }
  options:
    expose: true