image_annotator_profile_me:
  pattern: /
  defaults: { _controller: ImageAnnotatorBundle:Profile:show }

image_annotator_profile_user:
  pattern: /{userName}
  defaults: { _controller: ImageAnnotatorBundle:Profile:showSpecific }

image_annotator_profile_edit:
  pattern: /{userName}/edit
  defaults: { _controller: ImageAnnotatorBundle:Profile:edit }

image_annotator_profile_edit_avatar:
  pattern: /{userName}/edit/avatar
  defaults: { _controller: ImageAnnotatorBundle:Profile:updateAvatar }

image_annotator_profile_edit_password:
  pattern: /{userName}/edit/password
  defaults: { _controller: FOSUserBundle:ChangePassword:changePassword }
  requirements:
    _method: GET|POST
