image_annotator_homepage:
    path:     /
    defaults: { _controller: ImageAnnotatorBundle:Default:index }

ImageAnnotatorBundle_home:
  resource: "@ImageAnnotatorBundle/Resources/config/routing/home.yml"
  prefix: /home
    
ImageAnnotatorBundle_profile:
  resource: "@ImageAnnotatorBundle/Resources/config/routing/profile.yml"
  prefix: /profile
  
ImageAnnotatorBundle_annotations:
  resource: "@ImageAnnotatorBundle/Resources/config/routing/annotations.yml"
  prefix: /annotations
  
ImageAnnotatorBundle_images:
  resource: "@ImageAnnotatorBundle/Resources/config/routing/images.yml"
  prefix: /images